(() => {
'use strict';const $=id=>document.getElementById(id),KEY='japanese-pocket-v2',E=window.StudyEngine,data=window.STUDY_DATA;
let state={settings:{mode:'all',inverse:false,furigana:false,romaji:false,meaning:false,amount:100},stats:{},round:null};
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved){state={...state,...saved,settings:{...state.settings,...saved.settings}};}else{const old=JSON.parse(localStorage.getItem('japanese-pocket-v1'));if(old){state.settings={...state.settings,...old.settings};for(const id of old.known||[])state.stats[id]={streak:1,errors:0};if(old.started&&old.queue?.length)state.round={queue:old.queue,hard:{},mode:state.settings.mode,inverse:false};}}}catch{}
if(!state.settings.kinds)state.settings.kinds=state.settings.mode==='all'?['word','phrase','paragraph']:[state.settings.mode||'word'];
if(!state.settings.directions)state.settings.directions=state.settings.inverse?['reverse']:['forward'];
state.settings.kinds=state.settings.kinds.filter(k=>['word','phrase','paragraph'].includes(k));state.settings.directions=state.settings.directions.filter(k=>['forward','reverse'].includes(k));state.settings.amount=Math.max(100,Math.min(2000,Math.round((Number(state.settings.amount)||100)/100)*100));state.stats=state.stats&&typeof state.stats==='object'?state.stats:{};
const pool=()=>data.filter(c=>state.settings.kinds.includes(c.kind));
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{$('storageWarning').hidden=false;}}
function score(){const s=E.proficiency(data,state.stats);$('percent').textContent=(s.percent===100?'100':(Math.floor(s.percent*10)/10).toLocaleString('pt-BR'))+'%';$('masteryFill').style.width=s.percent+'%';}
const kindInputs={words:'word',phrases:'phrase',paragraphs:'paragraph'},directionInputs={forward:'forward',reverse:'reverse'};
function settings(){for(const k of ['furigana','romaji','meaning'])$(k).checked=!!state.settings[k];for(const [id,k]of Object.entries(kindInputs))$(id).checked=state.settings.kinds.includes(k);for(const [id,k]of Object.entries(directionInputs))$(id).checked=state.settings.directions.includes(k);$('amount').textContent=state.settings.amount;$('less').disabled=state.settings.amount<=100;$('more').disabled=state.settings.amount>=2000;const n=pool().length;const valid=n>0&&state.settings.directions.length>0;$('restart').disabled=!valid;$('newRound').disabled=!valid;$('available').textContent=!state.settings.kinds.length?'Selecione pelo menos um tipo de conteúdo.':!state.settings.directions.length?'Selecione pelo menos um sentido.':n?`${n} itens disponíveis · ${Math.min(n,state.settings.amount)} nesta rodada.`:'Este conteúdo ainda não tem cartões.';}
function closeSettings(){if($('settings').open)$('settings').close();$('lesson').hidden=false;document.body.classList.remove('config-open');$('settingsButton').setAttribute('aria-expanded','false');}
function openSettings(){settings();$('lesson').hidden=true;document.body.classList.add('config-open');$('settingsButton').setAttribute('aria-expanded','true');$('settings').showModal();}
function start(){if(!pool().length||!state.settings.directions.length){openSettings();return;}state.round={queue:E.pick(pool(),state.stats,state.settings.amount),hard:{},directions:[...state.settings.directions],nextInverse:Math.random()<.5,currentId:null};save();closeSettings();render();}
let revealed={};
function render(){revealed={};score();settings();const r=state.round;const c=data.find(c=>c.id===r?.queue[0]);$('japanese').replaceChildren();$('japanese').hidden=false;$('portuguesePrompt').hidden=true;$('romajiText').hidden=true;$('meaningText').hidden=true;$('completed').hidden=true;$('answers').hidden=!c;$('reveal').hidden=!c;$('card').classList.toggle('paragraph',c?.kind==='paragraph');
if(!c){$('japanese').hidden=true;$('completed').hidden=!pool().length;return;}
if(r.currentId!==c.id){r.currentId=c.id;r.currentInverse=r.directions.length===2?r.nextInverse:r.directions[0]==='reverse';r.nextInverse=!r.currentInverse;save();}
for(const seg of c.segments||[c.japanese]){if(typeof seg==='string')$('japanese').append(document.createTextNode(seg));else{const ruby=document.createElement('ruby');ruby.append(document.createTextNode(seg[0]));const rt=document.createElement('rt');rt.textContent=seg[1];ruby.append(rt);$('japanese').append(ruby);}}
$('portuguesePrompt').textContent=c.meaning;$('romajiText').textContent=c.romaji;$('meaningText').textContent=c.meaning;visibility();}
function visibility(){const inverse=!!state.round?.currentInverse,jp=!inverse||!!revealed.japanese;const kana=state.settings.furigana||revealed.furigana;$('portuguesePrompt').hidden=!inverse;$('japanese').hidden=!jp;document.querySelectorAll('ruby').forEach(r=>r.classList.toggle('hide-reading',!kana));$('romajiText').hidden=!(jp&&(state.settings.romaji||revealed.romaji));$('meaningText').hidden=inverse||!(state.settings.meaning||revealed.meaning);$('showJapanese').hidden=!inverse;$('showJapanese').disabled=jp;$('showKana').disabled=!jp||kana||!$('japanese').querySelector('ruby');$('showRomaji').disabled=!jp||!$('romajiText').hidden;$('showMeaning').hidden=inverse;$('showMeaning').disabled=!$('meaningText').hidden;}
function answer(known){if(!state.round?.queue.length)return;E.answer(state.round,state.stats,known);state.round.currentId=null;save();render();}
$('yes').onclick=()=>answer(true);$('no').onclick=()=>answer(false);
for(const [button,key]of[['showJapanese','japanese'],['showKana','furigana'],['showRomaji','romaji'],['showMeaning','meaning']])$(button).onclick=()=>{revealed[key]=true;visibility();};
$('settingsButton').onclick=openSettings;$('closeSettings').onclick=closeSettings;$('settings').addEventListener('cancel',event=>{event.preventDefault();closeSettings();});$('settings').addEventListener('close',()=>{$('lesson').hidden=false;document.body.classList.remove('config-open');$('settingsButton').setAttribute('aria-expanded','false');});
for(const key of ['furigana','romaji','meaning'])$(key).onchange=()=>{state.settings[key]=$(key).checked;save();if(state.round?.queue.length)visibility();};
for(const [id,key]of Object.entries(kindInputs))$(id).onchange=()=>{state.settings.kinds=Object.entries(kindInputs).filter(([i])=>$(i).checked).map(([,k])=>k);save();settings();};
for(const [id,key]of Object.entries(directionInputs))$(id).onchange=()=>{state.settings.directions=Object.entries(directionInputs).filter(([i])=>$(i).checked).map(([,k])=>k);save();settings();};
for(const [id,step]of[['less',-100],['more',100]])$(id).onclick=()=>{state.settings.amount=Math.max(100,Math.min(2000,state.settings.amount+step));save();settings();};
$('restart').onclick=start;$('newRound').onclick=start;
if(state.round){state.round.queue=(state.round.queue||[]).filter(id=>data.some(c=>c.id===id));state.round.hard=state.round.hard||{};if(!state.round.directions)state.round.directions=state.round.inverse?['reverse']:['forward'];save();render();}else start();
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();